### ISSUE TITLE
recurring issue that keeps going wrong over and over with module import

### ISSUE THREAD

**Issue by deborahduong** [singnet/reputation#250] opened 2019-06-17 16:28 UTC
I changed this to  from reputation.reputation_service_api import * along with the other two next to it and it worked.  Can we get this permanently changed this time???

 File "/home/dduong/reputation/reputation/reputation_service_api.py", line 26, in <module>
    from reputation_service_api import *
ModuleNotFoundError: No module named 'reputation_service_api'

**Comment by akolonin** [comment] 2019-06-18 07:04
@deborahduong , yes it is expected to be that way as we have it in the other files:
https://github.com/singnet/reputation/blob/master/reputation/reputation_base_api.py#L29

@nejc9921 , please make sure it is fixed and unit tests are working after the fix 
If you need your version of that, please be careful when committing and pushing the changes

**Comment by akolonin** [comment] 2019-06-20 06:35
@nejc9921 - is it fixed now?

**Comment by akolonin** [comment] 2019-06-24 06:50
@nejc9921 - Deborah Duong [1:40 PM]:
well 250 hurts me in the sense that I have to keep editing my own copy of the reputation system everytime I install, and thats probably true for anyone else using it

**Comment by nejc9921** [comment] 2019-06-24 12:58
Well we have it "from reputation.reputation_api import *" right now and if I got it right, this is what Deborah wanted? I do see that @akolonin had to fix it 4 days ago to get this back in, but I am not sure what was the issue 7 days ago, where (looking at historical changes) we still had "from reputation.reputation_api import *"?

**Comment by nejc9921** [comment] 2019-06-24 19:37
Deborah specified the issue as:

> File "/home/dduong/reputation/reputation/reputation_service_api.py", line 26, in
from reputation_service_api import *
ModuleNotFoundError: No module named 'reputation_service_api'

This means error at line 26, not line 28 ("from reputation_base_api import *").  So, this is a bit different nature of the problem. I also installed reputation-simulation module that Deborah created and tested the code - managed to reproduce the issue. This SHOULD fix it. Why should? Well, when I create Deborah's reputation-simulation fresh install on server, it saves the installation of reputation module in "/usr/local/lib/python3.7/site-packages/reputation/reputation_service_api.py", to which I don't have an access - so I cannot edit it. I had a similar problem around two months ago when I was first trying out her code - reputation is for some reason installed in the files inaccessible (at least for editing) to me. So, I hope this fixes the problem, it does pass unittests, but I could not test it on Deborah's code since that code directly downloads the code from Github and installs it on computer (server).

Now, the problem might also be at line 28, but unfortunately the code did not reach that line, so I cannot test this. I could fix this line as well, but the potential problem is that now it works and I would break it again, so for now I did not change anything.

**Comment by deborahduong** [comment] 2019-06-26 05:53
still not working

**Comment by akolonin** [comment] 2019-06-26 09:18
@tiero 
is installed via pip

https://github.com/singnet/reputation-simulation/blob/master/scripts/install#L11
scripts/install:11
```pip3 install -e git+https://github.com/singnet/reputation.git#egg=reputation```
singnet/reputation-simulation | Added by GitHub
Didnt read the whole thread yet, but I suppose you should install it in editable mode, so you can develop on the same machine the reputation and see the update module in simulation wihout pushing to github master to have reflected the changes
We should likely have an additional `install_dev` bash script that does all the same as `install`  (intended for production) except for installing via pip.

We assume reputation in development is already installed so you can manage indipendentely

**Comment by akolonin** [comment] 2019-06-27 03:00
@nejc9921 can you make the following one-line change?

from reputation.reputation_base_api import *
#from reputation_base_api import *

Like I have in here:
https://github.com/singnet/reputation/blob/master/reputation/aigents_reputation_api.py#L30

**Closed** 2019-06-27 10:10 UTC
Labels: bug, doing
